### ISSUE TITLE
사용자 인증 API 명세서 작성

### ISSUE THREAD

**Issue by ASak1104** [backendoori/ootw-backend#7]
리뷰 요청 - @Sehee-Lee-01 @shoeone96 

사용자 인증 API 명세서 1차 작성 완료했습니다
JWT를 사용하기 때문에 토큰 만료가 아닌 임의적인 로그아웃 기능을 위해선
블랙리스트 등록처럼 우회적인 접근 방식이 필요할 것 같습니다

# 명세서 작업 현황

- [x] 로그인 API
- [x] 회원가입 API
- [x] 로그아웃 API

#### Request

- Header

| Key | Value |
|--------|--------|
| Content-Type | application/json |
| Accept | application/json | 

- Body

```json
{
    "email": "user@email.com",
    "password": "user-password"
}
``` 

#### Response

- status code

| Code | Message |
|--------|--------|
| 200 | Success to login |
| 401 | Unauthorized |

- Body

```json
{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
}
``` 

#### Request

- Header

| Key | Value |
|--------|--------|
| Content-Type | application/json |
| Accept | application/json | 

- Body

```json
{
    "nickname": "user-nickname",
    "email": "user@email.com",
    "password": "user-password"
}
``` 

#### Response

- status code

| Code | Message |
|--------|--------|
| 201 | Success to signup |
| 400 | Bad request |

- Body

```json
{
    "nickname": "user-nickname",
    "email": "user@email.com",
    "image": null,
    "createdAt": "2019-07-10T08:21:15.000Z",
    "updatedAt": "2019-07-10T08:21:15.000Z"
}
``` 

#### Request

- Header

| Key | Value |
|--------|--------|
| Content-Type | application/json |
| Accept | application/json | 
| Authorization | Bearer {{jwt_token}} | 

#### Response

- status code

| Code | Message |
|--------|--------|
| 204 | Success to logout |
| 403 | Forbidden |

**Comment by Sehee-Lee-01** [comment]
### 회의 기록(2023.12.19)
- **토큰에 어떤 정보를 넣을 것이냐!** → 우선 유저 id만!
- **회원가입 API 응답 Body에 어떤 정보를 담을까** → 레퍼런스를 찾아봅시다.
