### ISSUE TITLE
게시글 API 명세서 작성

### ISSUE THREAD

**Issue by ASak1104** [backendoori/ootw-backend#8]
### 코멘트
에러 응답은 어떻게 하면 좋을지도 생각해보면 좋을 것 같습니다! 임의로 정해놓은 것이니,, 참고부탁드립니다!

### 게시글 API
- [x] 게시글 생성 API
- [x] 게시글 목록 API
- [x] 게시글 조회 API

## 게시글 생성 API

🚨 로그인한 사용자만 요청 가능

### Request

- Header

  | Key           | Value                |
  | ------------- | -------------------- |
  | Content-Type  | application/json     |
  | Accept        | application/json     |
  | Authroization | Bearer {{jwt_token}} |

- Body

  ```json
  {
    "title": "일교차가 심할 때 좋은 코디",
    "content": "일교차가 심할 땐 목도리 필수! 가디건도 챙기면 좋아요!",
    "image": null
  }
  ```

### Response

- status code

  | Code | Message           | Comment            |
  | ---- | ----------------- | ------------------ |
  | 201  | Success to create | 성공               |
  | 400  | Bad Request       | 잘못된 값으로 요청 |
  | 403  | Forbidden         | 익명 사용자인 경우 |

- Header & Body

  - Code: 201
  - 📷 `image는` 이미지 url이 들어온다.

    - Header

      | Key          | Value                     |
      | ------------ | ------------------------- |
      | Content-Type | application/json          |
      | Location     | {hostname}/api/v1/posts/1 |

    - Body

      ```json
      {
        "user_id": 1,
        "title": "일교차가 심할 때 좋은 코디",
        "content": "일교차가 심할 땐 목도리 필수! 가디건도 챙기면 좋아요!",
        "image": null,
        "created_at": "2021-10-17T14:00:00.000Z",
        "updated_at": "2021-10-17T14:00:00.000Z"
      }
      ```

  - Code: 400

    - Header

      | Key          | Value            |
      | ------------ | ---------------- |
      | Content-Type | application/json |

    - Body

      ```json
      {
        "message": "Bad Request",
        "errors": [
          {
            "field": "title",
            "message": "제목은 1글자 이상 30글자 이하로 입력해주세요."
          },
          {
            "field": "content",
            "message": "내용은 1글자 이상 300글자 이하로 입력해주세요."
          }
        ]
      }
      ```

  - Code: 403

    - Header

      | Key          | Value            |
      | ------------ | ---------------- |
      | Content-Type | application/json |

    - Body

      ```json
      {
        "message": "Forbidden"
      }
      ```

### `[GET] /api/v1/posts`

- 최신순 조회: `[GET] /api/v1/posts?sort=latest`

### Request

- Header
  | Key | Value |
  | ------------ | ---------------- |
  | Content-Type | application/json |
  | Accept | application/json |

- Body

  ```json
  {}
  ```

### Response

- status code
  | Code | Message |
  | ---- | ----------- |
  | 200 | Success |
  | 400 | Bad Request |
- Body

  - 📷 `image`는 이미지 url이 들어온다.
  - Code: 200

    ```json
    {
      "posts": [
        {
          "id": 1,
          "user_id": 1,
          "title": "일교차가 심할 때 좋은 코디",
          "content": "일교차가 심할 땐 목도리 필수! 가디건도 챙기면 좋아요!",
          "image": null,
          "created_at": "2021-10-17T14:00:00.000Z",
          "updated_at": "2021-10-17T14:00:00.000Z"
        },
        {
          "id": 2,
          "user_id": 1,
          "title": "OOTW 너무 좋은데요?",
          "content": "귀여운 캐릭터가 나왔어요!",
          "image": null,
          "created_at": "2021-10-17T14:00:00.000Z",
          "updated_at": "2021-10-17T14:00:00.000Z"
        }
      ]
    }
    ```

  - Code: 400

    ```json
    {
      "message": "Bad Request",
      "errors": [
        {
          "field": "sort",
          "message": "sort는 latest만 가능합니다."
        }
      ]
    }
    ```

### Request

- Header
  | Key | Value |
  | ------------ | ---------------- |
  | Content-Type | application/json |
  | Accept | application/json |

- Body

  ```json
  {}
  ```

### Response

- status code
  | Code | Message |
  | ---- | --------- |
  | 200 | Success |
  | 404 | Not Found |
- Body

  - 📷 `image`는 이미지 url이 들어온다.

  - code: 200

    ```json
    {
      "id": 1,
      "user_id": 1,
      "title": "일교차가 심할 때 좋은 코디",
      "content": "일교차가 심할 땐 목도리 필수! 가디건도 챙기면 좋아요!",
      "image": null,
      "created_at": "2021-10-17T14:00:00.000Z",
      "updated_at": "2021-10-17T14:00:00.000Z"
    }
    ```

  - code: 404

    ```json
    {
      "message": "Not Found"
    }
    ```

**Comment by Sehee-Lee-01** [comment]
`api/v1/posts` 에서
- sorting 할 기준이 두 개 이상이 되면 sorting 방법을 고민해봐도 좋을 것 같다.

user 정보는 
```json
{
    "userId":1
    "nickname":"nickname",
    "profile":"profile"
}
```

- post 정보에 추가

**Comment by Sehee-Lee-01** [comment]
### 회의 기록(2023.12.19)
- 메인 페이지 코디는 우선 최근순부터
- **게시글 생성  API**
    - 201 Body → post_id를 넣자(더 생각해보기)
    - 400 → BindingResult 에러 메시지 추출할 수 있는지 확인하기
- **게시글 목록/단건 조회 API**
    - 일단 페이지네이션 하지 않기 → 프론트 하면서 정해보기
    - 우선 초반에는 **쿼리 스트링 없이** 최신순으로 정렬 해서 보내기
    - 200 응답 Body
        - **user_id**보단 **유저 정보를 넣자.**
        - 지금은 무조건 조인으로 보내기→ 나중에 상황보고 반정규화 하기
