### ISSUE TITLE
Spring project Entity 초기 세팅

### ISSUE THREAD

**Issue by ASak1104** [backendoori/ootw-backend#9]
### Spring project Entity 초기 세팅

- [x] users, posts, avatar_appearance 테이블 DDL 스프링 프로젝트 내 추가
- [x] mysql DB container Dockerfile 이미지 생성
- [x] table에 매칭되는 ENTITY 클래스 생성

**Comment by Sehee-Lee-01** [comment]
### 회의 기록(2023.12.19)
- Spring 프로젝트와 DB 데이터 타입 호환 에러 → 우선 columnDefinition 정의로 해결

  - enum 타입(Spring) ↔ VARCHAR/ENUM(Mysql)      

  ![Image](https://github.com/spring-comes-to-us/outfit-of-the-weather/assets/85275893/6ba86eb8-6d4d-4eed-8a74-459c4add51b6)

  - boolean(Spring) ↔ tinyint(Mysql) 
    
  ![Image](https://github.com/spring-comes-to-us/outfit-of-the-weather/assets/85275893/2fb175de-8082-424a-a6bf-8416b9089360)
